#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "seqwin/graph.hpp"

namespace seqwin {

class ThreadPool;

/**
 * @brief Partial minimizer graph built by one worker thread.
 */
struct ThreadGraph {
    /**
     * Minimizer occurrences generated by this worker, stored in genomic position order.
     * Uses `std::vector` for `push_back()` support (exact kmer count is not known).
     */
    std::vector<Kmer> kmers;
    /**
     * Indices into `kmers`, grouped by minimizer hash.
     * The order is stable within each hash group, preserving the original genomic
     * position order of minimizers with the same hash.
     */
    NoInitArray<std::uint64_t> idx;
    /** Unsorted. */
    NoInitArray<Node> nodes;
    /** Unsorted. */
    NoInitArray<Edge> edges;
    /** FASTA record IDs of each assembly. */
    std::vector<std::vector<std::string>> ids_by_assembly;
    /** Total number of minimizers generated by this worker. */
    std::size_t n_kmers = 0;
    /** Global index of the first assembly assigned to this worker. */
    std::size_t start_assembly = 0;
};

/**
 * @brief Emit a message through Python's logging module.
 *
 * @param message Message to log.
 * @param level Logging level: `debug`, `info`, `warning`, `error`, or `critical`.
 */
void log_python(
    const std::string& message,
    const std::string& level = "info"
);

/**
 * @brief Merge thread-local minimizer graphs into a single graph.
 *
 * @param graphs Thread-local graphs produced during parallel graph construction.
 * @param n_assemblies Total number of input assemblies.
 * @param pool Thread pool used for parallel merge steps.
 * @return Fully merged minimizer graph.
 */
Graph merge_thread_graphs(
    std::vector<ThreadGraph>& graphs,
    std::size_t n_assemblies,
    ThreadPool& pool
);

Graph filter_kmers(
    const Kmer* kmers,
    const std::uint64_t* idx,
    const Node* nodes,
    std::size_t n_nodes,
    std::vector<std::uint64_t> used_hashes
);

} // namespace seqwin
