#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "seqwin/graph.hpp"

namespace seqwin {

class ThreadPool;

/**
 * @brief Thread-local minimizer graph node.
 *
 * `start` and `count` define a range in `ThreadGraph.kmers`.
 */
struct ThreadNode {
    /** Hash value of the minimizers represented by this node. */
    std::uint64_t hash;
    /** Start of entries in `ThreadGraph.kmers` for this node. */
    std::size_t start;
    /** Number of entries in `ThreadGraph.kmers` for this node. */
    std::size_t count;
    /** Number of target assemblies containing this minimizer hash. */
    std::uint32_t n_tar;
    /** Number of non-target assemblies containing this minimizer hash. */
    std::uint32_t n_neg;
    /** Worker thread that produced this node. Used by the merging step. */
    std::size_t thread_id;
};

/**
 * @brief Partial minimizer graph built by one worker thread.
 */
struct ThreadGraph {
    /** Minimizer occurrences generated by this worker, grouped by hash. */
    NoInitArray<Kmer> kmers;
    /** Unsorted. */
    NoInitArray<ThreadNode> nodes;
    /** Unsorted. */
    NoInitArray<Edge> edges;
    /** Thread-local cumulative FASTA record offsets by assembly. */
    std::vector<std::size_t> record_offsets;
    /** FASTA record IDs of each assembly. */
    std::vector<std::vector<std::string>> ids_by_assembly;
    /** Total number of minimizers generated by this worker. */
    std::size_t n_kmers = 0;
    /** Number of thread-local nodes materialized by this worker. */
    std::size_t n_nodes = 0;
    /** Global index of the first assembly assigned to this worker. */
    std::size_t start_assembly = 0;
    /** Global index one past the last assembly assigned to this worker. */
    std::size_t end_assembly = 0;
};

/**
 * @brief Per-thread maps from a minimizer hash to its start position in `Graph.kmers`.
 *
 * Each thread/hash pair owns a disjoint segment inside `Graph.kmers`.
 * When building `Graph.kmers` in the low memory mode, these starts are mutated as cursors.
 */
using KmerMaps = std::vector<std::unordered_map<std::uint64_t, std::size_t>>;

/**
 * @brief Emit a message through Python's logging module.
 *
 * @param message Message to log.
 * @param level Logging level: `debug`, `info`, `warning`, `error`, or `critical`.
 */
void log_python(
    const std::string& message,
    const std::string& level = "info"
);

/**
 * @brief Merge thread-local minimizer graphs into a single graph.
 *
 * @param graphs Thread-local graphs produced during parallel graph construction.
 * @param n_assemblies Total number of input assemblies.
 * @param pool Thread pool used for parallel merge steps.
 * @param low_memory If True, return k-mer position metadata to build `kmers` in the second pass.
 * @return Merged minimizer graph and k-mer maps. The second item is empty in standard mode.
 */
std::pair<Graph, KmerMaps> merge_thread_graphs(
    std::vector<ThreadGraph>& graphs,
    std::size_t n_assemblies,
    ThreadPool& pool,
    bool low_memory
);

Graph filter_kmers(
    const Kmer* kmers,
    const Node* nodes,
    std::size_t n_nodes,
    std::vector<std::uint64_t> used_hashes
);

} // namespace seqwin
