#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include <ankerl/unordered_dense.h>

#include "seqwin/graph.hpp"

namespace seqwin::internal {

class ThreadPool;

/**
 * @brief Worker-local minimizer graph node.
 *
 * `start` and `count` define a range in `WorkerGraph.kmers`.
 */
struct WorkerNode {
    /** Hash value of the minimizers represented by this node. */
    std::uint64_t hash;
    /** Start of entries in `WorkerGraph.kmers` for this node. */
    std::size_t start;
    /** Number of entries in `WorkerGraph.kmers` for this node. */
    std::size_t count;
    /** Logical worker that produced this node. Used by the merging step. */
    std::size_t worker_id;
};

/**
 * @brief Worker-local edge whose endpoints are minimizer hashes.
 */
struct WorkerEdge {
    /** Hash of the smaller minimizer endpoint. */
    std::uint64_t first;
    /** Hash of the larger minimizer endpoint. */
    std::uint64_t second;
    /** Number of assemblies where the endpoints are adjacent. */
    std::size_t weight;
};

/**
 * @brief Partial minimizer graph built by one logical worker.
 */
struct WorkerGraph {
    /** Minimizer occurrences generated by this worker, grouped by hash. */
    NoInitArray<Kmer> kmers;
    /** Unsorted. */
    NoInitArray<WorkerNode> nodes;
    /** Unsorted. */
    NoInitArray<WorkerEdge> edges;
    /** Worker-local cumulative FASTA record offsets by assembly. */
    std::vector<std::uint32_t> record_offsets;
    /** FASTA record IDs in this worker's global assembly order. */
    std::vector<std::string> record_ids;
    /** Total number of minimizers generated by this worker. */
    std::size_t n_kmers = 0;
    /** Number of worker-local nodes materialized by this worker. */
    std::size_t n_nodes = 0;
    /** Global index of the first assembly assigned to this worker. */
    std::size_t start_assembly = 0;
    /** Global index one past the last assembly assigned to this worker. */
    std::size_t end_assembly = 0;
};

using KmerMap = ankerl::unordered_dense::map<
    std::uint64_t,
    std::size_t,
    ankerl::unordered_dense::hash<std::uint64_t>,
    std::equal_to<std::uint64_t>,
    std::allocator<std::pair<std::uint64_t, std::size_t>>,
    ankerl::unordered_dense::bucket_type::big
>;

/**
 * @brief Per-worker maps from a minimizer hash to its start position in `Graph.kmers`.
 *
 * Each worker/hash pair owns a disjoint segment inside `Graph.kmers`.
 * When building `Graph.kmers` in the low memory mode, these starts are mutated as cursors.
 */
using KmerMaps = std::vector<KmerMap>;

/**
 * @brief Merge worker-local minimizer graphs into a single graph.
 *
 * @param graphs Worker-local graphs produced during parallel graph construction.
 * @param n_assemblies Total number of input assemblies.
 * @param pool Thread pool used for parallel merge steps.
 * @param low_memory If True, return k-mer position metadata to build `kmers` in the second pass.
 * @return Merged minimizer graph and k-mer maps. The second item is empty in standard mode.
 */
std::pair<Graph, KmerMaps> merge_worker_graphs(
    std::vector<WorkerGraph>& graphs,
    std::size_t n_assemblies,
    ThreadPool& pool,
    bool low_memory
);

} // namespace seqwin::internal
